### ISSUE TITLE
Questionsi with Translationni

### ISSUE THREAD

**Issue by Flloppis** [Paimon-Kawaii/MonitorEnhance#1]
Ah realli likesy tha features in tha mod! B-but.. ah- uhh-.. s-sadly cant understandsi most of whatsi said onna the popups.
Is therey way ta change translationsi inna game? 
![image](https://github.com/Paimon-Kawaii/MonitorEnhance/assets/157853816/34caec60-3b53-4adf-bf2c-1023ed7158b4)

**Comment by Paimon-Kawaii** [comment]
Yes, will add support for multilanguage.
Currently plan to add support for English and Chinese.
And soon you can change language by editing plugin's config.
