### ISSUE TITLE
关闭附近机关问题

### ISSUE THREAD

**Issue by 3qingmi** [Paimon-Kawaii/MonitorEnhance#2]
1、关闭附近机关，会把太空门也交互了，这个操作是有问题的。有时候把怪困住了，这个一键交互就废了。
2、还有能不能跟触控屏一样，有一个精准交互的按键。

**Comment by Paimon-Kawaii** [comment]
1、这个问题我有考虑过，主要是我不想再加一个键专门用于操控大门，实在不行我就把大门从机关里排除掉，有需要在终端操控吧。
2、精准交互是什么？我不是很理解。

**Comment by 3qingmi** [comment]
1、精准交互就是触控屏 LC-Touchscreen 这个mod的交互方式嘛，单独指定某个机关进行交互。
2、这个mod几乎覆盖塔台功能了，关太空门这个操作是可以使用精准交互的方式的。
3、或者把切换队友视角的E键改为 <-和->键，这样能前后切换队友，有时候切过头了可以回切，超大房间使用起来也方便一点。
4、然后把E键改为精准交互机关的按键，这样就交互太空门也不用到终端操作了。
* 主要也是Touchscreen用习惯了，并且Touchscreen这个需要按下E后才能使用鼠标左右键交互的方式，很大程度上避免了误操作，用起来比直接按键能交互的心理感受上要好一点。
* 其他功能体现不出来，但是传送队友是塔台的一个很敏感的操作，误传送还是很尴尬的，并且这个按下E后能做的功能非常灵活，可以按下E后点雷达，点队友传送，点机关，其实一个E加鼠标左右键几乎可以解决功能需求了。
* 例如：
1. E+LMB闪雷达，RMB发声；
2. E+LMB切到指定队友，RMB传送；
3. E+LMB关机关、RMB开机关
4. E+中键开关门
5. 这样简化了很多按键了，剩下做不到的就是"123456 左右切队友视角"、"Q快速切雷达"

**Comment by Paimon-Kawaii** [comment]
很不错的建议，我会把这些建议加入到下次更新的。

**Comment by Paimon-Kawaii** [comment]
>  关太空门这个操作是可以使用精准交互的方式的。  

另外关于这点，大门如果需要精确操控需要将监控视角切换至对应的大门，这个功能我不知道能不能实现；并且如果可以切到大门，我感觉操作量也有点多。

**Comment by 3qingmi** [comment]
> > 关太空门这个操作是可以使用精准交互的方式的。
> 
> 另外关于这点，大门如果需要精确操控需要将监控视角切换至对应的大门，这个功能我不知道能不能实现；并且如果可以切到大门，我感觉操作量也有点多。

1、如果需要将监控视角切换至对应的大门的话，确实不好操作，带来的问题是切换起来的过程是很难受的,操作起来甚至不如使用终端方便了。
2、我还以为是可以切到大门附近的队友视角，然后就能鼠标交互了，毕竟这个mod是能配合对讲机或者Helmet_Cameras使用的，因为看监控电视是塔台唯一的乐趣了。

3、而且做这个mod的目的是简化终端操作，还是加强终端这个还是区分出来才好的。当然简化操作就是加强塔台了，不过加强的幅度是需要把控的。
4、毕竟类似一键关闭机关这个种功能的mod也是有的，例如TerminalCommander，但是这个太超模了，很大程度降低了游戏难度。
5、哪怕我装了betterterminal这种能终端关门的mod，我也是不使用door命令的。因为通过飞船口的按键关门这个操作是一个很棒的游戏设计，也是在飞船上的一个游玩点，我个人是不想破坏这个体验的
6、上面只是个人看法，一点个人见解，别见怪哈

**Comment by Paimon-Kawaii** [comment]
主体功能大致完成了
